### ISSUE TITLE
Develop View Post View

### ISSUE THREAD

**Issue by Maker-Mark** [DataMascara/cisc3140-su19-project#18]
We need a way to display a post.
TODO:
-Given a post id, find all the associated comments, votes etc.
-Check-in with the front end team and review if the template for this view has been developed yet

**Comment by andrewalexgit** [comment]
@mary060196 Could you specify where the render in the test.py is I only see one for a search feature in the news feed

`# Note the optional 'search' argument passed to the function, and see what happens on the localhost's screen when you run the file!
@app.route("/newsfeed/")
def hello9():
    return render_template(
        "posts.html",
        name="Bla",
        trendPorts=trendPorts,
        port=port,
        search="My First Search!",
    )`

**Comment by mary060196** [comment]
@andrewalexgit , I do not quite understand what you are asking about in the `test.py`. What I said about
> Note the optional 'search' argument passed to the function, and see what happens on the localhost's screen when you run the file!
is that there is a search argument (`search`) that is being passed into the `render_template` function. However, I asked the Back End team to remove this argument from the function because the search feature is not implemented yet. Once it is implemented, I'll remind you about it. When `search` is passed to the template, a header is displayed on the screen that says: "Search Results for:...", which is all what it does.
Thank you!

**Comment by Maker-Mark** [comment]
Done and closed
