### ISSUE TITLE
Post related issues

### ISSUE THREAD

**Issue by AlekseyTitov99** [DataMascara/cisc3140-su19-project#43]
- For the comments to show you need to refresh the entire page (shouldnt be like that)
- Whenever you go into a post, the trending ports change to “DEMO” - https://prnt.sc/osbo7q
- Text box at the top, should be at the bottom (used by many companies that way)
- When creating a post, it asks for your username (even though im logged in) - https://prnt.sc/osbods

**Comment by mary060196** [comment]
Bullet point 1: There is no Ajax code used, which is why a comment cannot be submitted without redirection. The page should refresh automatically. Does it?
Bullet point 2: Ask the Back End team
Bullet point 3: Which text box?
Bullet point 4: This bug has been removed now.
Great thanks!

**Comment by mary060196** [comment]
@AlekseyTitov99 !
Bullet point 1: JavaScript code was added to the post details page so that every time you write a comment, it refreshes automatically, and the comment shows up without you needing to refresh the page!
Bullet point 2: The DEMO ports were replaced today with real ports by the Back End team.
The only issue that remains is, then, the comment text boxes on the post details page, which should be soon resolved by the Back End team.

**Comment by Maker-Mark** [comment]
> * For the comments to show you need to refresh the entire page (shouldnt be like that)
> * Whenever you go into a post, the trending ports change to “DEMO” - https://prnt.sc/osbo7q
> * Text box at the top, should be at the bottom (used by many companies that way)
> * When creating a post, it asks for your username (even though im logged in) - https://prnt.sc/osbods
@AlekseyTitov99 Thank you for finding and documenting these!
All related issues have been fixed, closing this for now
