### ISSUE TITLE
Voting On comments

### ISSUE THREAD

**Issue by kennish1997** [DataMascara/cisc3140-su19-project#50]
When upvoting/downvoting a comment, it just applies to the first comment
<img width="421" alt="Capture1" src="https://user-images.githubusercontent.com/49169064/62990814-5458a200-be1b-11e9-9913-510552c11555.PNG">

**Comment by mary060196** [comment]
Yea... the "reply" link should make a text area appear under the comment, like in the following image:
![image](https://user-images.githubusercontent.com/52957236/62992049-01cdb480-be20-11e9-8f7a-a4f2b2ef10f3.png)
But I guess the issue here is that the Server does not pass the right argument data structure (the JavaScript code that is used to display the text area reads the 'id' number of the comment, which the Back End apparently do not pass into the template. I'll assign @Maker-Mark here.

**Comment by mary060196** [comment]
@Maker-Mark , here is what a post dict should contain:
`postDict = {'id', 'title', 'portname', 'totalVotes', 'image', 'text', 'commentNum', 'dateCreated', 'username', 'avatarUrl', 'upOrDownvoted', 'comments': [{'id', 'totalVotes', 'dateCreated', 'username', 'avatarUrl', 'text', 'upOrDownvoted', 'comments' : [{'id', 'totalVotes', 'dateCreated', 'username', 'avatarUrl', 'text', 'upOrDownvoted'} ... ]} ... ]}}`
without these essential keys, the comments and the voting won't work. Try to fetch this information through functions, and then structure the data into this type of dict. Ellipsis (...) means that more comments can come within the list. Please look at the `test.py` to see the example.
Thank you for your consideration!

**Comment by Maker-Mark** [comment]
> Yea... the "reply" link should make a text area appear under the comment, like in the following image:
> ![image](https://user-images.githubusercontent.com/52957236/62992049-01cdb480-be20-11e9-8f7a-a4f2b2ef10f3.png)
> But I guess the issue here is that the Server does not pass the right argument data structure (the JavaScript code that is used to display the text area reads the 'id' number of the comment, which the Back End apparently do not pass into the template. I'll assign @Maker-Mark here.
Unfortunately, that's not how post's are stored (perhaps because then getting a post just as the post, ie for rendering the preview, could be arbitrarily hard. Instead there is a relationship between a list of comments and a post ID. I was able to change the template to get this working, reply are not working yet, but votes show up(they are buggy) and the reply box displays. 
- We are working on getting the comment reply working..
