### ISSUE TITLE
All Templates + Static Files Are In!

### ISSUE THREAD

**Issue by mary060196** [DataMascara/cisc3140-su19-project#56]
- `userInfo.html` was completed
- 404 Error Template Added
- Funny "No Password Reminders!" Template added. Link it to the "forgot password?" link on the maroon menu.
It is a great pleasure to work with such professionals as you are, guys!
- Close this issue when you read this message.

**Comment by Maker-Mark** [comment]
> * `userInfo.html` was completed
> * 404 Error Template Added
> * Funny "No Password Reminders!" Template added. Link it to the "forgot password?" link on the maroon menu.
>   It is a great pleasure to work with such professionals as you are, guys!
> * Close this issue when you read this message.

Hey Mary!
- I have just implemented the "forgot password" I love it ahaha
It's been a real pleasure from my end too, really.
I personally would love to upkeep and continue development of the site, we have all put so much into this, and it's really coming together.
- I was thinking we could finish things up, and, after a beta is done, we can pitch it to the CS department to have them feature it/ email students.
- Either way, the project is very impressive, I plan on doing all I can to keep it hosted so that it's live, and easy to reference for resumes and past/present experiences. 
I hope to have the opportunity to work with you again!
