### ISSUE TITLE
Autofill on Registration Page for Username/Email does not properly input to field

### ISSUE THREAD

**Issue by LoadingUser3** [DataMascara/cisc3140-su19-project#79]
When using Autofill on the registration page, whatever is selected does not register as an input.

Any sort of manipulation on the field(ex: adding and removing space, removing and re-adding a character, adding a character, etc) will make it register as an input.

The same occurs in the Email field. 

<img width="597" alt="Screen Shot 2019-08-16 at 1 04 27 PM" src="https://user-images.githubusercontent.com/47548948/63185016-e54f9900-c026-11e9-8038-4ef8e4138ea0.png">

It is still outlined in red at this point:

<img width="614" alt="Screen Shot 2019-08-16 at 1 04 46 PM" src="https://user-images.githubusercontent.com/47548948/63185092-1039ed00-c027-11e9-946a-b180f854acd1.png">

Testingagain = 12 Characters. Maybe my counting is wrong...:

<img width="603" alt="Screen Shot 2019-08-16 at 1 05 23 PM" src="https://user-images.githubusercontent.com/47548948/63185104-1b8d1880-c027-11e9-8290-160d85c6859d.png">

After manipulating the field, the error went away and I successfully logged in.

**Comment by LoadingUser3** [comment]
(How do I move this to the Registering User Backend Checking card besides copy-pasting?)

**Comment by mary060196** [comment]
@LoadingUser3 , you can assign people to see this post. There is a section at the top of the page called "Assignees", in which you can choose people who are part of the organization. This will make GitHub create a new email message and notify them about it. I am quite not sure how it can be added to the Backend card besides this.
Since yesterday, I've added a few more changes to the registration page. Could you check out if this specific problem is solved? Before you check, make sure to refresh the page twice, for any case.
Thank you very much, @LoadingUser3 ! Good luck on the final!

**Comment by mary060196** [comment]
@LoadingUser3 , please verify if the problem pertains. If it does, please re-open this issue and let know that the problem exists.
Thank you very much!
